### ISSUE TITLE
oscam-picons-converter

### ISSUE THREAD

**Issue by ghost** [s3n0/e2scripts#4]
In the oscam-picons-converter.log i can see 
Warning !
Total number of all SrvIDs is too high !
A lot of TPL-picons will be created !
Do you really want to continue ?
(y/n)
how can i press y on console if
oscam-picons-converter.py is running in background

<img width="663" alt="Screenshot 2021-12-26 120712" src="https://user-images.githubusercontent.com/2565966/147406154-ecd9ff25-cb7f-4cfe-8202-6c0de3777eab.png">

**Comment by s3n0** [comment]
Hi.

You're right, I'll throw this query out of the conversion python-script. 

I'll just leave a warning there ... and let the python-script continue to run.

Do you use OpenWebif shell-script ? To run oscam picons converter in the background ? Because you can run the conversion python-script directly (`oscam-picons-converter.py`), even via a terminal connection (via the Linux Shell) ... and not by calling it via OscamWebif shell-scripts :).

**Comment by ghost** [comment]
Thanks now it works

**Comment by s3n0** [comment]
BTW, thank you for reporting a minor error. 

This could also be solved by inserting into the algorithm the detection of whether the python-script was run via shell-script / in the background. If so, I would then exclude this "yes/no" query, only in this one case.

But at the moment I don't have much time to play with this code :-/.

Or simply add another argument "-y"  for override as yes through all queries.

Well, I think that will be enough, as it is now :-).
